after_success:
- codecov
install:
- pip install pytest
- pip install pytest-cov
- pip install codecov
- pip install docopt
- pip install requests
language: python
python: 3.7
script:
- py.test --cov=./
